[window]
dimensions.columns = 110
dimensions.lines = 40

padding.x = 8
padding.y = 8

opacity = 0.99

[font]
normal.family = "FiraCode Nerd Font Mono"
size = 9

[cursor]
style.shape = "Block"
style.blinking = "Always"

# Theme
[general]
import = [
    "./themes/everforest_dark.toml"
]
