[window]
dimensions.columns = 100
dimensions.lines = 36

padding.x = 8
padding.y = 8

opacity = 1

[font]
normal.family = "FiraCode Nerd Font Mono"
size = 9

[cursor]
style.shape = "Block"
style.blinking = "Always"

# Theme
[general]
import = [
    "./themes/night_owl.toml"
]
